export const types = {
    GET_FLOWER: 'GET_FLOWER',
    GET_CARTRIDGE: 'GET_CARTRIDGE',
    GET_EDIBLE: 'GET_EDIBLE',
    GET_EXTRACT: 'GET_EXTRACT',
    GET_MISC: 'GET_MISC',
    GET_PREROLL: 'GET_PREROLL',
    GET_TOPICAL: 'GET_TOPICAL',
    GET_MERCH: 'GET_MERCH',
    GET_BEVERAGE: 'GET_BEVERAGE',
    GET_PILL: 'GET_PILL',
    GET_TINCTURE: 'GET_TINCTURE',
    UPDATE_QTY: 'UPDATE_QTY',
    UPDATE_CART: 'UPDATE_CART',
    SET_ERRORS: 'SET_ERRORS',
    CLEAR_ERRORS: 'CLEAR_ERRORS'
}